import Foundation

// Docker's `.dockerignore` semantics, in Swift — the Mac side of workspace rules (`.dozignore`,
// `.dozreadonly`): `doz ignore check` / `show`, the warnings at create and start, the sandbox's counts.
// The guest's view daemon runs the SAME semantics in C (Guest/dozview/match/dozmatch.c); both pass
// Tests/Fixtures/dozignore-vectors.json — generated by the REAL moby/BuildKit Go code — in `make test`.
//
// Ports, behaviour for behaviour (the 599g probe, workspace probes/599g-*/patterns/):
//   moby/patternmatcher v0.6.1  ignorefile.ReadAll                         -> DockerIgnore.parse(_:)
//   moby/patternmatcher v0.6.1  New / Pattern.compile / match              -> DockerIgnore.init(patterns:)
//   ... MatchesOrParentMatches (package func: Clean, "." never matches)    -> isExcluded(_:)
//   ... MatchesUsingParentResults (what BuildKit's walker uses)            -> matchUsingParent(_:_:)
//   tonistiigi/fsutil filter.go: the SkipDir rule for an excluded dir      -> mayReincludeInside(_:)
//   Go path/filepath.Match (only to reproduce New's syntax check)          -> goMatch
//   Go path.Clean                                                          -> goClean
//
// LICENCE: those are ports, translated from Go to Swift by this project (a modified work), of moby/patternmatcher
// v0.6.1 (Copyright 2013-2018 Docker, Inc., Apache License 2.0 — Licences/moby-patternmatcher-v0.6.1.LICENSE and
// its NOTICE), tonistiigi/fsutil's filter rule (Copyright 2017 Tõnis Tiigi, MIT — Licences/tonistiigi-fsutil-*.LICENSE)
// and Go's path/filepath (Copyright 2009 The Go Authors, BSD-3-Clause — Licences/go-go1.25.0.LICENSE). This file is
// distributed under those licences; this project's own changes are also MIT.

typealias IgnoreBytes = ArraySlice<UInt8>
/// A pattern Docker refuses (Go's `filepath.ErrBadPattern`).
public struct BadIgnorePattern: Error, Sendable, Equatable {}
private let SL: UInt8 = 0x2F // "/"

// MARK: - Go helpers

/// Go `path.Clean` (== filepath.Clean on Unix).
func goClean(_ s: String) -> String {
    let p = Array(s.utf8)
    if p.isEmpty { return "." }
    let rooted = p[0] == SL
    var out: [UInt8] = rooted ? [SL] : []
    var r = rooted ? 1 : 0
    var dotdot = out.count
    while r < p.count {
        if p[r] == SL { r += 1 }
        else if p[r] == 0x2E && (r + 1 == p.count || p[r + 1] == SL) { r += 1 }
        else if p[r] == 0x2E && p[r + 1] == 0x2E && (r + 2 == p.count || p[r + 2] == SL) {
            r += 2
            if out.count > dotdot {
                var w = out.count - 1
                while w > dotdot && out[w] != SL { w -= 1 }
                out.removeSubrange(w...)
            } else if !rooted {
                if !out.isEmpty { out.append(SL) }
                out += [0x2E, 0x2E]; dotdot = out.count
            }
        } else {
            if (rooted && out.count != 1) || (!rooted && !out.isEmpty) { out.append(SL) }
            while r < p.count && p[r] != SL { out.append(p[r]); r += 1 }
        }
    }
    if out.isEmpty { return "." }
    return String(decoding: out, as: UTF8.self)
}

/// Go `strings.TrimSpace` (unicode.IsSpace == Unicode White_Space).
func goTrimSpace(_ s: Substring) -> Substring {
    let u = s.unicodeScalars
    guard let a = u.firstIndex(where: { !$0.properties.isWhitespace }) else { return "" }
    let b = u.lastIndex(where: { !$0.properties.isWhitespace })!
    return Substring(u[a...b])
}

private func decodeRune(_ s: IgnoreBytes) -> (UInt32, Int) {
    let b0 = s[s.startIndex]
    let n = b0 < 0x80 ? 1 : b0 < 0xE0 ? 2 : b0 < 0xF0 ? 3 : 4
    guard s.count >= n else { return (0xFFFD, 1) }
    if n == 1 { return (UInt32(b0), 1) }
    var r = UInt32(b0) & (0xFF >> (n + 1))
    for i in 1..<n { r = r << 6 | UInt32(s[s.startIndex + i] & 0x3F) }
    return (r, n)
}

private func getEsc(_ c: IgnoreBytes) throws -> (UInt32, IgnoreBytes) {
    var c = c
    guard let f = c.first, f != 0x2D, f != 0x5D else { throw BadIgnorePattern() }
    if f == 0x5C { c = c.dropFirst(); if c.isEmpty { throw BadIgnorePattern() } }
    let (r, n) = decodeRune(c)
    let rest = c.dropFirst(n)
    if rest.isEmpty { throw BadIgnorePattern() }
    return (r, rest)
}

private func scanChunk(_ p: IgnoreBytes) -> (Bool, IgnoreBytes, IgnoreBytes) {
    var p = p, star = false
    while p.first == 0x2A { p = p.dropFirst(); star = true }
    var inrange = false, i = p.startIndex
    while i < p.endIndex {
        switch p[i] {
        case 0x5C: if i + 1 < p.endIndex { i += 1 }
        case 0x5B: inrange = true
        case 0x5D: inrange = false
        case 0x2A: if !inrange { return (star, p[..<i], p[i...]) }
        default: break
        }
        i += 1
    }
    return (star, p, p[p.endIndex...])
}

private func matchChunk(_ chunkIn: IgnoreBytes, _ sIn: IgnoreBytes) throws -> IgnoreBytes? {
    var chunk = chunkIn, s = sIn, failed = false
    while let c = chunk.first {
        failed = failed || s.isEmpty
        switch c {
        case 0x5B:
            var r: UInt32 = 0
            if !failed { let (rr, n) = decodeRune(s); r = rr; s = s.dropFirst(n) }
            chunk = chunk.dropFirst()
            var negated = false
            if chunk.first == 0x5E { negated = true; chunk = chunk.dropFirst() }
            var match = false, nrange = 0
            while true {
                if chunk.first == 0x5D && nrange > 0 { chunk = chunk.dropFirst(); break }
                let (lo, c1) = try getEsc(chunk)
                chunk = c1
                var hi = lo
                if chunk.first == 0x2D { let (h, c2) = try getEsc(chunk.dropFirst()); hi = h; chunk = c2 }
                match = match || (lo <= r && r <= hi)
                nrange += 1
            }
            failed = failed || match == negated
        case 0x3F:
            if !failed { failed = s.first == SL; s = s.dropFirst(decodeRune(s).1) }
            chunk = chunk.dropFirst()
        default:
            if c == 0x5C { chunk = chunk.dropFirst(); if chunk.isEmpty { throw BadIgnorePattern() } }
            if !failed { failed = chunk.first != s.first; s = s.dropFirst() }
            chunk = chunk.dropFirst()
        }
    }
    return failed ? nil : s
}

/// Go `path/filepath.Match` on Unix (used by New purely for its error state).
func goMatch(_ pattern: String, _ name: String) throws -> Bool {
    var pat = IgnoreBytes(Array(pattern.utf8)), name = IgnoreBytes(Array(name.utf8))
    outer: while !pat.isEmpty {
        let (star, chunk, rest) = scanChunk(pat)
        pat = rest
        if star && chunk.isEmpty { return !name.contains(SL) }
        if let t = try matchChunk(chunk, name), t.isEmpty || !pat.isEmpty { name = t; continue }
        if star {
            var i = name.startIndex
            while i < name.endIndex && name[i] != SL {
                if let t = try matchChunk(chunk, name[(i + 1)...]) {
                    if pat.isEmpty && !t.isEmpty { i += 1; continue }
                    name = t; continue outer
                }
                i += 1
            }
        }
        return false
    }
    return name.isEmpty
}

/// Go `filepath.Dir`.
func goDir(_ p: String) -> String {
    guard let i = p.utf8.lastIndex(of: SL) else { return "." }
    return goClean(String(p[...i]))
}

/// patternmatcher's parent list: prefixes of strings.Split(filepath.Dir(file), "/"); none when Dir == ".".
func goAncestors(_ file: String) -> [String] {
    let d = goDir(file)
    if d == "." { return [] }
    let parts = d.split(separator: "/", omittingEmptySubsequences: false)
    return (1...parts.count).map { parts[..<$0].joined(separator: "/") }
}

// MARK: - Pattern

/// One pattern as patternmatcher compiles it (the RE2 source Go builds, run through ICU with the
/// dialect differences translated).
public final class DockerIgnorePattern: @unchecked Sendable {
    enum Kind { case unknown, exact, prefix, suffix, regexp }
    public let cleaned: String
    public let exclusion: Bool
    let bytes: [UInt8]
    private let lock = NSLock()
    private var kind = Kind.unknown
    private var regex: NSRegularExpression?
    private var compileFailed = false

    init(cleaned: String, exclusion: Bool) {
        self.cleaned = cleaned; self.bytes = Array(cleaned.utf8); self.exclusion = exclusion
    }

    /// patternmatcher.Pattern.compile with sl = "/". Builds the same RE2 source string Go builds.
    private func compile() throws {
        var re = "^", type = Kind.exact
        let sc = Array(cleaned.unicodeScalars)
        var k = 0, i = 0
        while k < sc.count {
            let ch = sc[k]; k += 1
            if ch == "*" {
                if k < sc.count && sc[k] == "*" {
                    k += 1
                    if k < sc.count && sc[k] == "/" { k += 1 }
                    if k == sc.count {
                        if type == .exact { type = .prefix } else { re += ".*"; type = .regexp }
                    } else { re += "(.*/)?"; type = .regexp }
                    if i == 0 { type = .suffix }
                } else { re += "[^/]*"; type = .regexp }
            } else if ch == "?" {
                re += "[^/]"; type = .regexp
            } else if ".+()$".unicodeScalars.contains(ch) {
                // Go's shouldEscape lists `.+()|{}$` too, but its bitset overflows for bytes >= 64: `|`, `{`
                // and `}` reach RE2 RAW (alternation, counted repetition) — Docker's real behaviour.
                re += "\\" + String(ch)
            } else if ch == "\\" {
                if k < sc.count { re += "\\" + String(sc[k]); k += 1; type = .regexp } else { re += "\\" }
            } else if ch == "[" || ch == "]" {
                re += String(ch); type = .regexp
            } else { re += String(ch) }
            i += 1
        }
        if type == .regexp {
            re += "$"
            regex = try NSRegularExpression(pattern: try Self.re2ToICU(re))
        }
        kind = type
    }

    /// Translate the RE2 source to ICU where the dialects differ: unescaped `$` outside a class is
    /// end-of-text in RE2 (`\z` in ICU); inside a class ICU treats `[` and `&&`/`--` as set syntax;
    /// RE2's escape grammar is stricter (non-ASCII / unknown letters are errors) and its \d \s \w \b are ASCII.
    static func re2ToICU(_ re: String) throws -> String {
        let s = Array(re.unicodeScalars)
        var out = "", i = 0, inClass = false, classStart = 0
        func isOct(_ j: Int) -> Bool { j < s.count && ("0"..."7").contains(s[j]) }
        var prevRepeat = false            // RE2 refuses a repetition of a repetition (`*{2}`, `{2}{3}`)
        /// RE2's `{n}` `{n,}` `{n,m}` at `j` (n, m ≤ 1000, no leading zeros): its end index, or nil (a literal `{`).
        func repeatForm(_ j: Int) throws -> Int? {
            func num(_ k: inout Int) -> Int? {
                let start = k
                while k < s.count, ("0"..."9").contains(s[k]) { k += 1 }
                guard k > start else { return nil }
                let t = String(String.UnicodeScalarView(s[start..<k]))
                if t.count >= 2 && t.first == "0" { return nil }
                return Int(t.prefix(8)) ?? Int.max
            }
            var k = j + 1
            guard let n = num(&k) else { return nil }
            var m: Int? = n
            if k < s.count, s[k] == "," {
                k += 1
                if k < s.count, s[k] == "}" { m = -1 } else { guard let mm = num(&k) else { return nil }; m = mm }
            }
            guard k < s.count, s[k] == "}" else { return nil }
            if n > 1000 || (m ?? 0) > 1000 || (m != -1 && m! < n) { throw BadIgnorePattern() }
            return k
        }
        while i < s.count {
            let c = s[i]
            if !inClass {
                if c == "{" {
                    if let end = try repeatForm(i) {
                        if prevRepeat { throw BadIgnorePattern() }
                        out += String(String.UnicodeScalarView(s[i...end])); i = end + 1; prevRepeat = true; continue
                    }
                    out += "\\{"; i += 1; prevRepeat = false; continue
                }
                if c == "}" { out += "\\}"; i += 1; prevRepeat = false; continue }
                if c == "*" || c == "?" {
                    if prevRepeat { throw BadIgnorePattern() }
                    out += String(c); i += 1; prevRepeat = true; continue
                }
                if c == "|" { out += "|"; i += 1; prevRepeat = false; continue }
                prevRepeat = false
            }
            if c == "\\" && i + 1 < s.count {
                let e = s[i + 1]; i += 2
                if !e.isASCII { throw BadIgnorePattern() }
                let perl: [Unicode.Scalar: (String, Bool)] = ["d": ("0-9", false), "D": ("0-9", true), "s": ("\\t\\n\\f\\r ", false),
                    "S": ("\\t\\n\\f\\r ", true), "w": ("0-9A-Za-z_", false), "W": ("0-9A-Za-z_", true)]
                if let (set, neg) = perl[e] {
                    out += inClass && !neg ? set : "[" + (neg ? "^" : "") + set + "]"
                } else if e == "v" { out += "\\x{0B}" }
                else if "afnrt".unicodeScalars.contains(e) { out += "\\" + String(e) }
                else if "bBAz".unicodeScalars.contains(e) {
                    if inClass { throw BadIgnorePattern() } // RE2 rejects assertions inside a class
                    let w = "[0-9A-Za-z_]" // RE2's \b is ASCII-word based; ICU's is Unicode
                    out += e == "b" ? "(?:(?<=\(w))(?!\(w))|(?<!\(w))(?=\(w)))"
                         : e == "B" ? "(?:(?<=\(w))(?=\(w))|(?<!\(w))(?!\(w)))" : "\\" + String(e)
                }
                else if e == "x" || e == "p" || e == "P" {
                    out += "\\" + String(e)
                    if i < s.count && s[i] == "{" { while i < s.count && s[i] != "}" { out += String(s[i]); i += 1 }; if i < s.count { out += "}"; i += 1 } }
                    else if i < s.count { let n = e == "x" ? 2 : 1; for _ in 0..<n where i < s.count { out += String(s[i]); i += 1 } }
                } else if e == "Q" && !inClass {
                    out += "\\Q"
                    while i < s.count && !(s[i] == "\\" && i + 1 < s.count && s[i + 1] == "E") { out += String(s[i]); i += 1 }
                    out += "\\E"; i = min(i + 2, s.count)
                } else if e == "0" || (("1"..."7").contains(e) && isOct(i)) {
                    var v = Int(e.value) - 48
                    for _ in 0..<2 where isOct(i) { v = v * 8 + Int(s[i].value) - 48; i += 1 }
                    out += "\\x{" + String(v, radix: 16) + "}"
                } else if e.properties.isAlphabetic || ("0"..."9").contains(e) { throw BadIgnorePattern() }
                else { out += "\\" + String(e) }
                continue
            }
            if !inClass {
                if c == "$" { out += "\\z" }
                else if c == "[" {
                    out += "["; inClass = true; i += 1
                    if i < s.count && s[i] == "^" { out += "^"; i += 1 }
                    classStart = i; continue
                } else { out += String(c) }
            } else {
                if c == "]" && i > classStart { out += "]"; inClass = false }
                else if c == "[" && i + 1 < s.count && s[i + 1] == ":" { out += "[" } // POSIX [:alpha:]
                else if c == "[" || c == "&" || c == "]" { out += "\\" + String(c) }
                else if c == "-" && i + 1 < s.count && s[i + 1] == "-" { out += "\\-" }
                else { out += String(c) }
            }
            i += 1
        }
        return out
    }

    /// Compile now (thread-safe, once). Throws when the pattern's regexp does not compile.
    func prepare() throws {
        lock.lock(); defer { lock.unlock() }
        if compileFailed { throw BadIgnorePattern() }
        if kind != .unknown { return }
        do { try compile() } catch { compileFailed = true; throw BadIgnorePattern() }
    }

    public func match(_ path: String) throws -> Bool {
        try prepare()
        let p = Array(path.utf8)
        switch kind {
        case .exact: return p == bytes
        case .prefix: return p.starts(with: bytes.dropLast(2))
        case .suffix:
            let suffix = bytes.dropFirst(2)
            if p.count >= suffix.count && p.suffix(suffix.count).elementsEqual(suffix) { return true }
            return suffix.first == SL && p.elementsEqual(suffix.dropFirst())
        case .regexp:
            let ns = path as NSString
            return regex!.firstMatch(in: path, range: NSRange(location: 0, length: ns.length)) != nil
        case .unknown: throw BadIgnorePattern()
        }
    }
}

// MARK: - Matcher

/// A `.dockerignore` matcher: patternmatcher.New over a list of patterns.
public struct DockerIgnore: Sendable {
    public let patterns: [DockerIgnorePattern]
    let hasExclusions: Bool
    /// fsutil: false when some exception (minus trailing /** or /*) contains a glob char.
    let onlyPrefixExceptions: Bool
    /// Lenient: a pattern whose regexp does not compile never matches (instead of an error).
    let lenient: Bool

    /// One line of a rules file as `ignorefile.ReadAll` keeps it: the pattern ("!"-prefixed for an
    /// exception) and its 1-based line number in the file.
    public struct Line: Sendable, Equatable {
        public var pattern: String
        public var line: Int
    }

    /// ignorefile.ReadAll: BOM strip, `#` in column 1 = comment, TrimSpace, `!` (+TrimSpace), Clean, strip leading `/`.
    public static func parse(_ text: String) -> [String] { parseLines(text).map(\.pattern) }

    public static func parseLines(_ text: String) -> [Line] {
        // bufio.ScanLines: split on \n, drop one trailing \r, no empty final token. Byte-wise (Swift's "\r\n" is one Character).
        var lines = Array(text.utf8).split(separator: 0x0A, omittingEmptySubsequences: false)
        if lines.last?.isEmpty == true { lines.removeLast() }
        var out: [Line] = []
        for (n, rawBytes) in lines.enumerated() {
            var b = rawBytes
            if b.last == 0x0D { b = b.dropLast() }
            if n == 0 && b.starts(with: [0xEF, 0xBB, 0xBF]) { b = b.dropFirst(3) }
            let line = Substring(String(decoding: b, as: UTF8.self))
            if b.first == 0x23 { continue } // "#" in column 1 (before trimming)
            var p = goTrimSpace(line)
            if p.isEmpty { continue }
            let invert = p.utf8.first == 0x21
            if invert { p = goTrimSpace(Substring(p.utf8.dropFirst())) }
            var pat = String(p)
            if !pat.isEmpty {
                pat = goClean(pat)
                if pat.utf8.count > 1 && pat.utf8.first == SL { pat = String(Substring(pat.utf8.dropFirst())) }
            }
            out.append(Line(pattern: invert ? "!" + pat : pat, line: n + 1))
        }
        return out
    }

    /// patternmatcher.New — throws `BadIgnorePattern` exactly when Docker refuses the list.
    public init(patterns raw: [String]) throws {
        var ps: [DockerIgnorePattern] = []
        for r in raw {
            guard let p = try Self.newPattern(r) else { continue }
            ps.append(p)
        }
        self.init(compiled: ps, lenient: false)
    }

    /// Like `init(patterns:)`, but a pattern Docker would refuse is DROPPED (its index and why are
    /// returned) and a pattern whose regexp does not compile never matches — what the guest view does.
    public static func lenient(_ raw: [String]) -> (DockerIgnore, dropped: [(index: Int, reason: String)]) {
        var ps: [DockerIgnorePattern] = [], dropped: [(Int, String)] = []
        for (i, r) in raw.enumerated() {
            do {
                guard let p = try newPattern(r) else { continue }
                do { try p.prepare() } catch { dropped.append((i, "not a valid pattern")); continue }
                ps.append(p)
            } catch {
                dropped.append((i, r.trimmingCharacters(in: .whitespaces) == "!" ? "a lone ! names nothing" : "not a valid pattern"))
            }
        }
        return (DockerIgnore(compiled: ps, lenient: true), dropped)
    }

    private static func newPattern(_ r: String) throws -> DockerIgnorePattern? {
        var p = String(goTrimSpace(Substring(r)))
        if p.isEmpty { return nil }
        p = goClean(p)
        var excl = false
        if p.utf8.first == 0x21 {
            if p.utf8.count == 1 { throw BadIgnorePattern() }
            excl = true; p = String(Substring(p.utf8.dropFirst()))
        }
        _ = try goMatch(p, ".")
        return DockerIgnorePattern(cleaned: p, exclusion: excl)
    }

    init(compiled ps: [DockerIgnorePattern], lenient: Bool) {
        patterns = ps
        self.lenient = lenient
        hasExclusions = ps.contains { $0.exclusion }
        onlyPrefixExceptions = !ps.contains { $0.exclusion && Self.stripGlob($0.cleaned).contains(where: { "*[]?^\\".contains($0) }) }
    }

    public init(file text: String) throws { try self.init(patterns: Self.parse(text)) }

    private static func stripGlob(_ s: String) -> String {
        var s = s
        if s.hasSuffix("/**") { s.removeLast(3) }
        if s.hasSuffix("/*") { s.removeLast(2) }
        return s
    }

    private func m(_ pat: DockerIgnorePattern, _ path: String) throws -> Bool {
        if lenient { return (try? pat.match(path)) ?? false }
        return try pat.match(path)
    }

    /// patternmatcher.MatchesOrParentMatches (package-level: Clean first, "." never excluded).
    /// Last matching pattern wins; a pattern "matches" if it matches the path or any ancestor dir.
    public func isExcluded(_ path: String) throws -> Bool {
        let file = goClean(path)
        if file == "." { return false }
        let ancestors = goAncestors(file)
        var matched = false
        for pat in patterns where pat.exclusion == matched {
            var hit = try m(pat, file)
            if !hit { hit = ancestors.contains { (try? m(pat, $0)) == true } }
            if hit { matched = !pat.exclusion }
        }
        return matched
    }

    /// patternmatcher.MatchesUsingParentResults — the walker form; `parent` is the parent dir's result
    /// (nil at the top). `decider` is the index of the pattern that set the result last (nil: none did).
    public func matchUsingParent(_ path: String, _ parent: [Bool]?) throws -> (excluded: Bool, info: [Bool], decider: Int?) {
        var matched = false, decider: Int? = nil
        var info = [Bool](repeating: false, count: patterns.count)
        for (i, pat) in patterns.enumerated() {
            var hit = parent?[i] ?? false
            if !hit {
                if pat.exclusion != matched { continue }
                hit = try m(pat, path)
                if !hit && parent == nil { hit = goAncestors(path).contains { (try? m(pat, $0)) == true } }
            }
            info[i] = hit
            if hit { matched = !pat.exclusion; decider = i }
        }
        return (matched, info, decider)
    }

    /// fsutil's SkipDir rule for an EXCLUDED dir: may an exception re-include something inside it?
    public func mayReincludeInside(_ dir: String) -> Bool {
        if !hasExclusions { return false }
        if !onlyPrefixExceptions { return true }
        let dirSlash = Array((dir + "/").utf8)
        return patterns.contains { $0.exclusion && Array((Self.stripGlob($0.cleaned) + "/").utf8).starts(with: dirSlash) }
    }

    /// Must a walker look inside `dir`? True unless the dir is excluded AND no exception can reach inside it.
    public func shouldDescend(_ dir: String) throws -> Bool {
        try !isExcluded(dir) || mayReincludeInside(goClean(dir))
    }

    /// Simulates fsutil.Walk(ExcludePatterns) over a path list (dirs end in "/"); returns emitted paths in walk order.
    public func walk(_ tree: [String]) throws -> [String] {
        var dirs = Set<String>(), children: [String: Set<String>] = [:]
        for t in tree {
            let isDir = t.hasSuffix("/")
            let p = isDir ? String(t.dropLast()) : t
            let comps = p.split(separator: "/").map(String.init)
            for i in 1...comps.count {
                let sub = comps[..<i].joined(separator: "/")
                children[i == 1 ? "" : comps[..<(i - 1)].joined(separator: "/"), default: []].insert(sub)
                if i < comps.count || isDir { dirs.insert(sub) }
            }
        }
        var out: [String] = []
        var stack: [(sep: String, path: String, info: [Bool], called: Bool)] = []
        func visit(_ parent: String) throws {
            let kids = (children[parent] ?? []).sorted { Array($0.utf8).lexicographicallyPrecedes(Array($1.utf8)) }
            for path in kids {
                let isDir = dirs.contains(path)
                while let last = stack.last, !path.hasPrefix(last.sep) { stack.removeLast() }
                let r = try matchUsingParent(path, stack.last?.info)
                if r.excluded && isDir && onlyPrefixExceptions && !mayReincludeInside(path) { continue }
                if !r.excluded {
                    for i in stack.indices where !stack[i].called { stack[i].called = true; out.append(stack[i].path) }
                    out.append(path)
                }
                if isDir { stack.append((path + "/", path, r.info, !r.excluded)); try visit(path) }
            }
        }
        try visit("")
        return out
    }
}
