/*
 * dozmatch.c — `.dozignore` / `.dozreadonly` pattern semantics: see include/dozmatch.h for the
 * contract and the Go functions each part ports. The reference port these were checked against is
 * probes/599g-i170-DOZER-DOZIGNORE/patterns/DozIgnore.swift; the vectors are
 * Tests/Fixtures/dozignore-vectors.json (generated by the real Go code).
 *
 * LICENCE: a port, translated from Go to C by this project (a modified work), of
 *   - moby/patternmatcher v0.6.1 (Pattern compile/match, ignorefile parsing) — Copyright 2013-2018 Docker, Inc.,
 *     Apache License 2.0 (Licences/moby-patternmatcher-v0.6.1.LICENSE, its NOTICE beside it), and
 *   - Go's path.Clean / path/filepath.Match — Copyright 2009 The Go Authors, BSD-3-Clause
 *     (Licences/go-go1.25.0.LICENSE).
 * This file is distributed under those licences; this project's own changes are also MIT.
 */
#include "dozmatch.h"
#include "dozre.h"

#include <stdlib.h>
#include <string.h>

enum { K_UNKNOWN, K_EXACT, K_PREFIX, K_SUFFIX, K_REGEXP, K_BAD };

struct dm_pattern {
    char *text;      /* cleaned, without "!" */
    size_t len;
    int exclusion;
    int kind;
    dmre *re;
};

/* ---------------------------------------------------------------- Go helpers */

/* unicode.IsSpace == Unicode White_Space. */
static int is_white_space(uint32_t r) {
    return (r >= 0x09 && r <= 0x0D) || r == 0x20 || r == 0x85 || r == 0xA0 || r == 0x1680 ||
           (r >= 0x2000 && r <= 0x200A) || r == 0x2028 || r == 0x2029 || r == 0x202F || r == 0x205F ||
           r == 0x3000;
}

/* strings.TrimSpace on s[0..n): sets *start, returns the trimmed length. */
static size_t trim_space(const char *s, size_t n, size_t *start) {
    const unsigned char *u = (const unsigned char *)s;
    size_t i = 0, a = n, b = 0;
    int seen = 0;
    while (i < n) {
        size_t w;
        uint32_t r = dm__utf8_decode(u + i, n - i, &w);
        int sp = !(r == 0xFFFD && w == 1) && is_white_space(r);
        if (!sp) { if (!seen) { a = i; seen = 1; } b = i + w; }
        i += w;
    }
    if (!seen) { *start = 0; return 0; }
    *start = a;
    return b - a;
}

/* Go path.Clean of p[0..n) into out (capacity >= n + 2); returns the length (out NUL-terminated). */
static size_t clean_into(const char *p, size_t n, char *out) {
    if (n == 0) { out[0] = '.'; out[1] = 0; return 1; }
    int rooted = p[0] == '/';
    size_t w = 0, r = 0, dotdot = 0;
    if (rooted) { out[w++] = '/'; r = 1; dotdot = 1; }
    while (r < n) {
        if (p[r] == '/') r++;
        else if (p[r] == '.' && (r + 1 == n || p[r + 1] == '/')) r++;
        else if (p[r] == '.' && p[r + 1] == '.' && (r + 2 == n || p[r + 2] == '/')) {
            r += 2;
            if (w > dotdot) {
                w--;
                while (w > dotdot && out[w] != '/') w--;
            } else if (!rooted) {
                if (w > 0) out[w++] = '/';
                out[w++] = '.'; out[w++] = '.';
                dotdot = w;
            }
        } else {
            if ((rooted && w != 1) || (!rooted && w != 0)) out[w++] = '/';
            for (; r < n && p[r] != '/'; r++) out[w++] = p[r];
        }
    }
    if (w == 0) { out[0] = '.'; w = 1; }
    out[w] = 0;
    return w;
}

char *dm_clean(const char *path) {
    size_t n = strlen(path);
    char *out = malloc(n + 2);
    if (!out) return NULL;
    clean_into(path, n, out);
    return out;
}

/* ---- Go path/filepath.Match (Unix), only for New's error state. 1 / 0, -1 = ErrBadPattern. */

typedef struct { const char *p; size_t n; } span;

static int get_esc(span *c, uint32_t *r) {
    if (c->n == 0 || c->p[0] == '-' || c->p[0] == ']') return -1;
    if (c->p[0] == '\\') { c->p++; c->n--; if (c->n == 0) return -1; }
    size_t w;
    *r = dm__utf8_decode((const unsigned char *)c->p, c->n, &w);
    int bad = *r == 0xFFFD && w == 1;
    c->p += w; c->n -= w;
    if (c->n == 0) bad = 1;
    return bad ? -1 : 0;
}

/* matchChunk: 1 ok (rest in *s), 0 failed, -1 bad pattern. */
static int match_chunk(span chunk, span *s) {
    int failed = 0;
    while (chunk.n > 0) {
        failed = failed || s->n == 0;
        char c = chunk.p[0];
        if (c == '[') {
            uint32_t r = 0;
            if (!failed) {
                size_t w;
                r = dm__utf8_decode((const unsigned char *)s->p, s->n, &w);
                s->p += w; s->n -= w;
            }
            chunk.p++; chunk.n--;
            int negated = 0;
            if (chunk.n > 0 && chunk.p[0] == '^') { negated = 1; chunk.p++; chunk.n--; }
            int match = 0, nrange = 0;
            for (;;) {
                if (chunk.n > 0 && chunk.p[0] == ']' && nrange > 0) { chunk.p++; chunk.n--; break; }
                uint32_t lo, hi;
                if (get_esc(&chunk, &lo) < 0) return -1;
                hi = lo;
                if (chunk.p[0] == '-') {
                    chunk.p++; chunk.n--;
                    if (get_esc(&chunk, &hi) < 0) return -1;
                }
                match = match || (lo <= r && r <= hi);
                nrange++;
            }
            failed = failed || match == negated;
        } else if (c == '?') {
            if (!failed) {
                failed = s->p[0] == '/';
                size_t w;
                dm__utf8_decode((const unsigned char *)s->p, s->n, &w);
                s->p += w; s->n -= w;
            }
            chunk.p++; chunk.n--;
        } else {
            if (c == '\\') {
                chunk.p++; chunk.n--;
                if (chunk.n == 0) return -1;
            }
            if (!failed) {
                failed = chunk.p[0] != s->p[0];
                s->p++; s->n--;
            }
            chunk.p++; chunk.n--;
        }
    }
    return failed ? 0 : 1;
}

static void scan_chunk(span *pat, int *star, span *chunk) {
    *star = 0;
    while (pat->n > 0 && pat->p[0] == '*') { pat->p++; pat->n--; *star = 1; }
    int inrange = 0;
    size_t i;
    for (i = 0; i < pat->n; i++) {
        char c = pat->p[i];
        if (c == '\\') { if (i + 1 < pat->n) i++; }
        else if (c == '[') inrange = 1;
        else if (c == ']') inrange = 0;
        else if (c == '*' && !inrange) break;
    }
    chunk->p = pat->p; chunk->n = i;
    pat->p += i; pat->n -= i;
}

static int go_match(const char *pattern, size_t plen, const char *name, size_t nlen) {
    span pat = { pattern, plen }, nm = { name, nlen };
    while (pat.n > 0) {
        int star;
        span chunk;
        scan_chunk(&pat, &star, &chunk);
        if (star && chunk.n == 0) return memchr(nm.p, '/', nm.n) == NULL;
        span t = nm;
        int ok = match_chunk(chunk, &t);
        if (ok == 1 && (t.n == 0 || pat.n > 0)) { nm = t; continue; }
        if (ok < 0) return -1;
        if (star) {
            int cont = 0;
            for (size_t i = 0; i < nm.n && nm.p[i] != '/'; i++) {
                span t2 = { nm.p + i + 1, nm.n - i - 1 };
                int ok2 = match_chunk(chunk, &t2);
                if (ok2 == 1) {
                    if (pat.n == 0 && t2.n > 0) continue;
                    nm = t2; cont = 1; break;
                }
                if (ok2 < 0) return -1;
            }
            if (cont) continue;
        }
        return 0;
    }
    return nm.n == 0;
}

/* ---------------------------------------------------------------- ignorefile.ReadAll */

void dm_free_lines(char **out, int *lines, int n) {
    if (out) for (int i = 0; i < n; i++) free(out[i]);
    free(out);
    free(lines);
}

int dm_parse_file(const char *text, size_t len, char ***out, int **lines) {
    *out = NULL; *lines = NULL;
    int n = 0, cap = 0;
    char **v = NULL;
    int *ln = NULL;
    size_t pos = 0;
    int lineno = 0;
    char *buf = malloc(len + 3);
    if (!buf) return -1;
    while (pos < len) {
        const char *nl = memchr(text + pos, '\n', len - pos);
        size_t end = nl ? (size_t)(nl - text) : len;
        const char *b = text + pos;
        size_t bl = end - pos;
        pos = nl ? end + 1 : len;
        if (bl > 0 && b[bl - 1] == '\r') bl--;
        if (lineno == 0 && bl >= 3 && (unsigned char)b[0] == 0xEF && (unsigned char)b[1] == 0xBB &&
            (unsigned char)b[2] == 0xBF) { b += 3; bl -= 3; }
        lineno++;
        if (bl > 0 && b[0] == '#') continue;
        size_t st, tl = trim_space(b, bl, &st);
        if (tl == 0) continue;
        b += st;
        int invert = b[0] == '!';
        if (invert) { tl = trim_space(b + 1, tl - 1, &st); b = b + 1 + st; }
        size_t pl = 0;
        char *pat = buf + 1;
        if (tl > 0) {
            pl = clean_into(b, tl, pat);
            if (pl > 1 && pat[0] == '/') { pat++; pl--; }
        }
        char *s = malloc(pl + 2);
        if (!s) goto oom;
        size_t o = 0;
        if (invert) s[o++] = '!';
        memcpy(s + o, pat, pl);
        s[o + pl] = 0;
        if (n == cap) {
            int nc = cap ? cap * 2 : 16;
            char **nv = realloc(v, (size_t)nc * sizeof *nv);
            if (!nv) { free(s); goto oom; }
            v = nv;
            int *nln = realloc(ln, (size_t)nc * sizeof *nln);
            if (!nln) { free(s); goto oom; }
            ln = nln;
            cap = nc;
        }
        v[n] = s; ln[n] = lineno; n++;
    }
    free(buf);
    *out = v; *lines = ln;
    return n;
oom:
    free(buf);
    dm_free_lines(v, ln, n);
    return -1;
}

/* ---------------------------------------------------------------- New */

static void free_pattern(dm_pattern *p) {
    if (!p) return;
    free(p->text);
    dmre_free(p->re);
    free(p);
}

void dm_set_free(dm_set *s) {
    if (!s) return;
    for (int i = 0; i < s->n; i++) free_pattern(s->pats[i]);
    free(s->pats);
    s->pats = NULL; s->n = 0;
}

/* fsutil patternWithoutTrailingGlob: the length of p without a trailing slash-star-star, then without a
 * trailing slash-star. */
static size_t strip_glob_len(const char *p, size_t n) {
    if (n >= 3 && memcmp(p + n - 3, "/**", 3) == 0) n -= 3;
    if (n >= 2 && memcmp(p + n - 2, "/*", 2) == 0) n -= 2;
    return n;
}

int dm_set_init(dm_set *s, const char *const *patterns, int n, int lenient, int *bad,
                dm_bad_pattern_cb cb, void *ctx) {
    memset(s, 0, sizeof *s);
    s->lenient = lenient ? 1 : 0;
    s->only_prefix_exceptions = 1;
    if (bad) *bad = -1;
    if (n > 0) {
        s->pats = calloc((size_t)n, sizeof *s->pats);
        if (!s->pats) return -1;
    }
    for (int i = 0; i < n; i++) {
        const char *raw = patterns[i];
        size_t st, tl = trim_space(raw, strlen(raw), &st);
        if (tl == 0) continue;
        char *c = malloc(tl + 2);
        if (!c) goto fail_nomem;
        size_t cl = clean_into(raw + st, tl, c);
        int excl = 0;
        const char *why = NULL;
        char *body = c;
        if (c[0] == '!') {
            if (cl == 1) why = "illegal exclusion pattern: \"!\"";
            else { excl = 1; body = c + 1; cl--; }
        }
        if (!why && go_match(body, cl, ".", 1) < 0) why = "syntax error in pattern";
        if (why) {
            if (cb) cb(ctx, i, raw, why);
            free(c);
            if (lenient) continue;
            if (bad) *bad = i;
            dm_set_free(s);
            return -1;
        }
        dm_pattern *p = calloc(1, sizeof *p);
        if (!p) { free(c); goto fail_nomem; }
        if (body != c) memmove(c, body, cl + 1);
        p->text = c; p->len = cl; p->exclusion = excl; p->kind = K_UNKNOWN;
        s->pats[s->n++] = p;
    }
    for (int i = 0; i < s->n; i++) {
        dm_pattern *p = s->pats[i];
        if (!p->exclusion) continue;
        s->has_exclusions = 1;
        size_t sl = strip_glob_len(p->text, p->len);
        for (size_t k = 0; k < sl; k++) {
            char ch = p->text[k];
            if (ch == '*' || ch == '[' || ch == ']' || ch == '?' || ch == '^' || ch == '\\') {
                s->only_prefix_exceptions = 0;
                break;
            }
        }
    }
    return 0;
fail_nomem:
    if (bad) *bad = -1;
    dm_set_free(s);
    return -1;
}

const char *dm_pattern_text(const dm_set *s, int i) { return s->pats[i]->text; }
int dm_pattern_is_exclusion(const dm_set *s, int i) { return s->pats[i]->exclusion; }

/* ---------------------------------------------------------------- Pattern.compile / match */

/* Build Go's RE2 source for the pattern (sl = "/"), set the kind, compile the regexp form.
 * 0 ok, DMRE_ESYNTAX, DMRE_ENOMEM. */
static int compile_pattern(dm_pattern *p) {
    const unsigned char *s = (const unsigned char *)p->text;
    size_t n = p->len;
    /* worst case: 5 output bytes per input byte (a single star becomes "[^/]" plus a star) */
    char *re = malloc(n * 6 + 8);
    if (!re) return DMRE_ENOMEM;
    size_t o = 0;
    re[o++] = '^';
    int type = K_EXACT;
    size_t k = 0;
    /* text/scanner: next rune (invalid byte = U+FFFD, width 1); a leading BOM is skipped. */
#define PEEK(r, w) ((k < n) ? ((r) = dm__utf8_decode(s + k, n - k, &(w)), 1) : 0)
    uint32_t r;
    size_t w;
    if (PEEK(r, w) && r == 0xFEFF) k += w;
    for (int i = 0; k < n; i++) {
        (void)PEEK(r, w);
        k += w;
        uint32_t nr; size_t nw;
        if (r == '*') {
            if (PEEK(nr, nw) && nr == '*') {
                k += nw;
                if (PEEK(nr, nw) && nr == '/') k += nw;
                if (k >= n) {
                    if (type == K_EXACT) type = K_PREFIX;
                    else { memcpy(re + o, ".*", 2); o += 2; type = K_REGEXP; }
                } else { memcpy(re + o, "(.*/)?", 6); o += 6; type = K_REGEXP; }
                if (i == 0) type = K_SUFFIX;
            } else { memcpy(re + o, "[^/]*", 5); o += 5; type = K_REGEXP; }
        } else if (r == '?') {
            memcpy(re + o, "[^/]", 4); o += 4; type = K_REGEXP;
        } else if (r == '.' || r == '+' || r == '(' || r == ')' || r == '$') {
            /* Go's shouldEscape is a bitset over `.+()|{}$` whose `1 << (b/8)` overflows its byte for
             * b >= 64: `|`, `{` and `}` are NOT escaped, so they reach RE2 raw (alternation, counted
             * repetition). Ported as Go behaves, not as it was meant. */
            re[o++] = '\\'; re[o++] = (char)r;
        } else if (r == '\\') {
            if (PEEK(nr, nw)) {
                k += nw;
                re[o++] = '\\';
                o += dm__utf8_encode(nr, (unsigned char *)re + o);
                type = K_REGEXP;
            } else re[o++] = '\\';
        } else if (r == '[' || r == ']') {
            re[o++] = (char)r; type = K_REGEXP;
        } else {
            o += dm__utf8_encode(r, (unsigned char *)re + o);
        }
    }
#undef PEEK
    int rc = 0;
    if (type == K_REGEXP) {
        re[o++] = '$';
        rc = dmre_compile(re, o, &p->re);
    }
    free(re);
    if (rc == DMRE_OK) p->kind = type;
    else if (rc == DMRE_ESYNTAX) p->kind = K_BAD;
    return rc;
}

int dm_set_compile_all(dm_set *s, dm_bad_pattern_cb cb, void *ctx) {
    int bad = 0;
    for (int i = 0; i < s->n; i++) {
        dm_pattern *p = s->pats[i];
        if (p->kind == K_UNKNOWN) compile_pattern(p);
        if (p->kind == K_UNKNOWN || p->kind == K_BAD) {
            bad++;
            if (cb) cb(ctx, i, p->text, p->kind == K_BAD ? "pattern does not compile" : "out of memory");
        }
    }
    return bad;
}

/* Pattern.match: 1 / 0 / DM_MATCH_ERROR (lenient: never an error). */
static int pattern_match(const dm_set *set, dm_pattern *p, const char *path, size_t n) {
    if (p->kind == K_UNKNOWN) compile_pattern(p);
    switch (p->kind) {
    case K_EXACT: return n == p->len && memcmp(path, p->text, n) == 0;
    case K_PREFIX: return n >= p->len - 2 && memcmp(path, p->text, p->len - 2) == 0;
    case K_SUFFIX: {
        const char *suf = p->text + 2;
        size_t sl = p->len - 2;
        if (n >= sl && memcmp(path + n - sl, suf, sl) == 0) return 1;
        return suf[0] == '/' && n == sl - 1 && memcmp(path, suf + 1, n) == 0;
    }
    case K_REGEXP: {
        int m = dmre_match(p->re, path, n);
        if (m < 0) return set->lenient ? 0 : DM_MATCH_ERROR;
        return m;
    }
    default: return set->lenient ? 0 : DM_MATCH_ERROR;
    }
}

/* Match p against each ancestor of `dir` (Go: prefixes of strings.Split(dir, "/")); errors ignored. */
static int match_ancestors(const dm_set *set, dm_pattern *p, const char *dir, size_t dl) {
    for (size_t k = 0; k <= dl; k++) {
        if (k == dl || dir[k] == '/')
            if (pattern_match(set, p, dir, k) == 1) return 1;
    }
    return 0;
}

#define DM_STACK_PATH 512

/* filepath.Dir(file) into a buffer: returns its length, or (size_t)-1 when it is "." (no ancestors). */
static size_t go_dir(const char *file, size_t n, char *buf) {
    size_t i = n;
    while (i > 0 && file[i - 1] != '/') i--;
    size_t dl = clean_into(file, i, buf);
    if (dl == 1 && buf[0] == '.') return (size_t)-1;
    return dl;
}

static int matches_or_parent(dm_set *s, const char *file, size_t n, const char *dir, size_t dl) {
    int matched = 0;
    for (int i = 0; i < s->n; i++) {
        dm_pattern *p = s->pats[i];
        if (p->exclusion != matched) continue;
        int m = pattern_match(s, p, file, n);
        if (m == DM_MATCH_ERROR) return DM_MATCH_ERROR;
        if (!m && dl != (size_t)-1) m = match_ancestors(s, p, dir, dl);
        if (m) matched = !p->exclusion;
    }
    return matched ? DM_YES : DM_NO;
}

int dm_is_excluded(dm_set *s, const char *path) {
    size_t n = strlen(path);
    char stackbuf[2 * DM_STACK_PATH];
    char *mem = stackbuf;
    if (2 * (n + 2) > sizeof stackbuf) {
        mem = malloc(2 * (n + 2));
        if (!mem) return s->lenient ? DM_NO : DM_MATCH_ERROR;
    }
    char *file = mem, *dir = mem + n + 2;
    size_t fl = clean_into(path, n, file);
    int rc = DM_NO;
    if (!(fl == 1 && file[0] == '.')) {
        size_t dl = go_dir(file, fl, dir);
        rc = matches_or_parent(s, file, fl, dir, dl);
    }
    if (mem != stackbuf) free(mem);
    return rc;
}

int dm_match_parent(dm_set *s, const char *path, const uint8_t *parent_info, uint8_t *out_info, int *decider) {
    size_t n = strlen(path);
    if (decider) *decider = -1;
    if (s->n == 0) return DM_NO;
    char stackbuf[DM_STACK_PATH];
    char *dir = NULL;
    size_t dl = (size_t)-1;
    int matched = 0, rc = DM_NO;
    memset(out_info, 0, (size_t)s->n);
    for (int i = 0; i < s->n; i++) {
        dm_pattern *p = s->pats[i];
        int m = parent_info ? parent_info[i] != 0 : 0;
        if (!m) {
            if (p->exclusion != matched) continue;
            m = pattern_match(s, p, path, n);
            if (m == DM_MATCH_ERROR) { rc = DM_MATCH_ERROR; goto out; }
            if (!m && !parent_info) {
                if (!dir) {
                    dir = n + 2 <= sizeof stackbuf ? stackbuf : malloc(n + 2);
                    if (!dir) { rc = s->lenient ? DM_NO : DM_MATCH_ERROR; goto out; }
                    dl = go_dir(path, n, dir);
                }
                if (dl != (size_t)-1) m = match_ancestors(s, p, dir, dl);
            }
        }
        out_info[i] = (uint8_t)(m ? 1 : 0);
        if (m) { matched = !p->exclusion; if (decider) *decider = i; }
    }
    rc = matched ? DM_YES : DM_NO;
out:
    if (dir && dir != stackbuf) free(dir);
    return rc;
}

int dm_may_reinclude_inside(const dm_set *s, const char *dir) {
    if (!s->has_exclusions) return 0;
    if (!s->only_prefix_exceptions) return 1;
    size_t dl = strlen(dir);
    for (int i = 0; i < s->n; i++) {
        const dm_pattern *p = s->pats[i];
        if (!p->exclusion) continue;
        size_t sl = strip_glob_len(p->text, p->len);
        /* HasPrefix(stripped + "/", dir + "/") */
        if (sl >= dl && memcmp(p->text, dir, dl) == 0 && (sl == dl || p->text[dl] == '/'))
            return 1;
    }
    return 0;
}
