#!/bin/bash
# third-party-licences.sh — 611: the licence texts and NOTICEs a binary distribution of doz must carry, written into
# OUT_DIR (release.sh puts them in the tarball as libexec/doz/licences/; Homebrew installs them with the keg):
#
#   LICENSE                    Dozer Sandbox's own (MIT)
#   NOTICE                     the repository's NOTICE (attributions the Apache-2.0 dependencies require)
#   THIRD-PARTY-LICENSES.txt   every resolved Swift package's licence text AND its NOTICE file, verbatim, from the exact
#                              checkout SwiftPM built (.build/checkouts, the versions in Package.resolved), then the
#                              guest binaries' and the dashboard's vendored components' licences
#
# It FAILS when a pin in Package.resolved has no checkout or no licence file — a dependency added without its licence
# never ships silently. Run after a build (the checkouts exist). Usage: Scripts/third-party-licences.sh OUT_DIR
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:?OUT_DIR}"
cd "$ROOT"
mkdir -p "$OUT"
cp LICENSE "$OUT/LICENSE"
cp NOTICE "$OUT/NOTICE"
T="$OUT/THIRD-PARTY-LICENSES.txt"
{
    echo "Third-party software in doz (Dozer Sandbox) — the licence texts and NOTICE files, verbatim."
    echo "Generated by Scripts/third-party-licences.sh from the exact sources this build used. See LICENCES.md"
    echo "in the source repository for what each component is and how it is used."
} > "$T"
pins="$(python3 -c "
import json
for p in json.load(open('Package.resolved'))['pins']:
    print(p['identity'], p['location'], p['state'].get('version') or p['state'].get('revision', '')[:12])")"
missing=""
while read -r id url ver; do
    d=".build/checkouts/$id"
    [[ -d "$d" ]] || d="$(find .build/checkouts -maxdepth 1 -iname "$id" | head -1)"
    if [[ -z "$d" || ! -d "$d" ]]; then missing+="$id (no checkout) "; continue; fi
    lic="$(find "$d" -maxdepth 1 -type f \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' \) | sort | head -1)"
    # zstd: dual-licensed BSD-3-Clause OR GPL-2.0 (LICENSE is the BSD text; COPYING the GPL) — used under BSD.
    [[ "$id" == zstd ]] && lic="$d/LICENSE"
    [[ -n "$lic" ]] || { missing+="$id (no licence file) "; continue; }
    {
        printf '\n\n================================================================================\n'
        printf '%s %s — %s\n' "$id" "$ver" "$url"
        printf '================================================================================\n\n'
        cat "$lic"
        for n in $(find "$d" -maxdepth 1 -type f \( -iname 'NOTICE*' \) | sort); do
            printf '\n---- %s ----\n\n' "$(basename "$n")"
            cat "$n"
        done
    } >> "$T"
done <<<"$pins"
[[ -z "$missing" ]] || { printf 'x third-party-licences: %s\n' "$missing" >&2; exit 1; }
# Licence texts no checkout carries (BoringSSL, LibYAML) and those of what this project PORTS (Go, moby/patternmatcher,
# fsutil) — fetched verbatim at pinned revisions (Licences/SOURCES.md; the audit checks their sha256).
for f in Licences/*.LICENSE Licences/*.NOTICE; do
    {
        printf '\n\n================================================================================\n'
        printf '%s — source: %s\n' "$(basename "$f")" "$(grep -F "\`$(basename "$f")\`" Licences/SOURCES.md | awk -F' \\| ' '{print $3}')"
        printf '================================================================================\n\n'
        cat "$f"
    } >> "$T"
done
# The guest binaries (static Linux executables doz copies into each sandbox) and the dashboard's vendored files.
{
    printf '\n\n================================================================================\n'
    printf 'The guest binaries — deckhold, doznet, dozview (this project, MIT) — statically link:\n'
    printf '================================================================================\n\n'
    printf '%s\n' "- musl libc (MIT) — https://musl.libc.org/ — Copyright © 2005-2020 Rich Felker, et al." \
        "- deckhold only: libghostty-vt from Ghostty (MIT) — https://github.com/ghostty-org/ghostty — Copyright © 2024 Mitchell Hashimoto, Ghostty contributors;" \
        "  with simdutf (Apache-2.0 OR MIT, used under MIT), Highway (Apache-2.0 OR BSD-3-Clause, used under Apache-2.0)" \
        "  and LLVM libc++/libc++abi/libunwind (Apache-2.0 WITH LLVM-exception)." \
        "- dozview's pattern matcher (match/dozmatch.c, dozre.c) is a port of moby/patternmatcher v0.6.1 (Apache-2.0)" \
        "  and Go's regexp/syntax, path and path/filepath (BSD-3-Clause, Copyright 2009 The Go Authors) — texts above." \
        "- dozview's and doz's case-folding tables are derived from the Unicode Character Database (Unicode License v3):" \
        "  Copyright © 1991-2025 Unicode, Inc. — https://www.unicode.org/license.txt"
    for v in Sources/DozerWeb/WebSource/vendor/*/; do
        name="$(basename "$v")"
        lf="$(python3 -c "import json,sys; d=json.load(open('$v/VENDOR.json')); print(d.get('licenceFile','LICENSE'), d.get('licence',''), d.get('version',''))")"
        set -- $lf
        printf '\n\n================================================================================\n'
        printf 'The dashboard: %s %s (%s) — served to your browser by doz ui\n' "$name" "${3:-}" "${2:-}"
        printf '================================================================================\n\n'
        cat "$v/$1"
    done
} >> "$T"
printf 'ok third-party-licences: %s (%s packages + the guest binaries + the dashboard'"'"'s vendored files)\n' "$OUT" "$(wc -l <<<"$pins" | tr -d ' ')"
