/*
 * dozmatch.h — `.dozignore` / `.dozreadonly` pattern semantics in C: the guest view daemon's matcher.
 *
 * ONE contract with the Swift matcher (Sources/DozerKit/WorkspaceRules.swift): both must pass
 * Tests/Fixtures/dozignore-vectors.json (generated by the REAL moby/BuildKit Go code) and
 * Tests/Fixtures/dozfold-vectors.json, in `make test`.
 *
 * Ports, behaviour for behaviour:
 *   moby/patternmatcher v0.6.1  ignorefile.ReadAll            -> dm_parse_file
 *   moby/patternmatcher v0.6.1  New (incl. filepath.Match's syntax check against ".") -> dm_set_init
 *   moby/patternmatcher v0.6.1  MatchesOrParentMatches (package-level: Clean, "." never) -> dm_is_excluded
 *   moby/patternmatcher v0.6.1  MatchesUsingParentResults (BuildKit's walker form)    -> dm_match_parent
 *   tonistiigi/fsutil filter.go  the SkipDir rule for an excluded dir                  -> dm_may_reinclude_inside
 * Pattern.compile builds a Go RE2 regular expression; the regexp form is matched by a small RE2-subset
 * engine here (exactly the constructs that compile can produce), with RE2's parse errors.
 *
 * Folding (owner decision D2): on a case-insensitive Mac volume the view ALSO evaluates folded
 * patterns against the folded path, and a path is excluded when EITHER evaluation excludes it (it can
 * only ever hide more than Docker). dm_fold = per scalar: full canonical decomposition, then simple case
 * folding, then decomposition again, then canonical ordering — tables generated by
 * Scripts/gen-dozfold-tables.py (also into Sources/DozerKit/DozFoldTables.swift).
 *
 * Pure C99 + libc; no allocation in the match path except the regexp engine's bounded scratch; no
 * global state; safe to call from several threads on one const dm_set once dm_set_compile_all ran.
 * MIT (this package).
 */
#ifndef DOZMATCH_H
#define DOZMATCH_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Results of a match. */
#define DM_NO          0
#define DM_YES         1
#define DM_MATCH_ERROR (-1)   /* a pattern this match reached does not compile (Go: ErrBadPattern at match time) */

typedef struct dm_pattern dm_pattern;   /* opaque */

typedef struct dm_set {
    dm_pattern **pats;
    int n;
    int has_exclusions;            /* any "!" pattern */
    int only_prefix_exceptions;    /* fsutil: no exception (minus a trailing slash-** or slash-*) holds a glob char */
    int lenient;                   /* 1: a pattern that does not compile never matches (DM_MATCH_ERROR is never returned) */
} dm_set;

/* ignorefile.ReadAll: BOM strip on line 1, '#' in COLUMN 1 = comment (before trimming), TrimSpace,
 * '!' + TrimSpace again, filepath.Clean, one leading '/' removed. Returns the count of patterns (each
 * malloc'd, "!"-prefixed for an exception) in *out, and each one's 1-based source line in *lines.
 * Free with dm_free_lines. Never fails (returns -1 only on allocation failure). */
int dm_parse_file(const char *text, size_t len, char ***out, int **lines);
void dm_free_lines(char **out, int *lines, int n);

/* patternmatcher.New over n patterns: 0, or -1 when New would fail (a bare "!", or a pattern for
 * which Go's filepath.Match(pattern, ".") returns ErrBadPattern). On failure *bad (if non-NULL) is
 * the index of the offending pattern. The set is empty after a failure (nothing to free).
 * With lenient = 1, a pattern that New would refuse is DROPPED instead (its index reported through
 * the optional callback) and the call succeeds. */
typedef void (*dm_bad_pattern_cb)(void *ctx, int index, const char *pattern, const char *why);
int dm_set_init(dm_set *s, const char *const *patterns, int n, int lenient, int *bad,
                dm_bad_pattern_cb cb, void *ctx);
void dm_set_free(dm_set *s);

/* Compile every pattern now (Go compiles lazily, on first match). Returns the count of patterns that
 * do not compile (each reported through cb when given). Call before sharing a set between threads. */
int dm_set_compile_all(dm_set *s, dm_bad_pattern_cb cb, void *ctx);

/* The pattern's text as New cleaned it (no "!"), and whether it is an exception. */
const char *dm_pattern_text(const dm_set *s, int i);
int dm_pattern_is_exclusion(const dm_set *s, int i);

/* patternmatcher.MatchesOrParentMatches (the package-level function: Clean first, "." never excluded).
 * DM_YES / DM_NO / DM_MATCH_ERROR. */
int dm_is_excluded(dm_set *s, const char *path);

/* patternmatcher.MatchesUsingParentResults — BuildKit's walker. `path` is the cleaned relative path
 * ("a/b/c"); parent_info is the PARENT directory's out_info (NULL at the top level, where ancestors
 * are matched as MatchesOrParentMatches does). out_info must hold s->n bytes. *decider (optional) is
 * the index of the pattern that decided the result (the last one that set it), or -1 when none did.
 * DM_YES / DM_NO / DM_MATCH_ERROR. */
int dm_match_parent(dm_set *s, const char *path, const uint8_t *parent_info, uint8_t *out_info, int *decider);

/* fsutil's SkipDir rule for an EXCLUDED directory: 1 when an exception may re-include something
 * inside `dir` (so a walker must still look inside it), else 0. */
int dm_may_reinclude_inside(const dm_set *s, const char *dir);

/* Go path.Clean, malloc'd. */
char *dm_clean(const char *path);

/* Folding (see the header comment). Both return malloc'd NUL-terminated UTF-8. Invalid UTF-8 bytes
 * are copied through unchanged. dm_fold_pattern folds like dm_fold but copies the scalar after each
 * backslash unchanged (an escape letter keeps its meaning: \A is not \a). */
char *dm_fold(const char *s);
char *dm_fold_pattern(const char *p);

#ifdef __cplusplus
}
#endif
#endif
